<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.foryuum</groupId>
  <artifactId>frontend</artifactId>
  <packaging>war</packaging>
  <version>1.0.0</version>
  <name>For Yuum project frontend</name>
  <url>http://maven.apache.org</url>
  
  <properties>
    <maven.compiler.source>21</maven.compiler.source>
    <maven.compiler.target>21</maven.compiler.target>
	<org.springframework-version>6.2.0</org.springframework-version>
    <timestamp>${maven.build.timestamp}</timestamp>
    <maven.build.timestamp.format>yyyyMMdd</maven.build.timestamp.format>
    <env>dev</env>
  </properties>
  
  <dependencies>
	<!-- Spring framework -->
	<dependency>
	    <groupId>org.springframework</groupId>
	    <artifactId>spring-web</artifactId>
	    <version>${org.springframework-version}</version>
	</dependency>
			
	<dependency>
	    <groupId>org.springframework</groupId>
	    <artifactId>spring-webmvc</artifactId>
	    <version>${org.springframework-version}</version>
	</dependency>
	
	<dependency>
	    <groupId>jakarta.annotation</groupId>
	    <artifactId>jakarta.annotation-api</artifactId>
	    <version>3.0.0</version> 
	</dependency>

	<!-- Servlet -->
	<dependency>
	    <groupId>jakarta.servlet</groupId>
	    <artifactId>jakarta.servlet-api</artifactId>
	    <version>6.0.0</version>
	    <scope>compile</scope>
	</dependency>

  	<!-- LOG 관련 -->
	<dependency>
	    <groupId>ch.qos.logback</groupId>
	    <artifactId>logback-classic</artifactId>
	    <version>1.5.12</version>
	    <scope>compile</scope>
	</dependency>
	
	<dependency>
	    <groupId>org.slf4j</groupId>
	    <artifactId>slf4j-api</artifactId>
	    <version>2.0.15</version>
	</dependency>
	
	<dependency>
	    <groupId>org.bgee.log4jdbc-log4j2</groupId>
	    <artifactId>log4jdbc-log4j2-jdbc4.1</artifactId>
	    <version>1.16</version>
	</dependency>

	<dependency>
		<groupId>org.lazyluke</groupId>
		<artifactId>log4jdbc-remix</artifactId>
		<version>0.2.7</version>
	</dependency>
	
	<!-- JSON -->
	<dependency>
	    <groupId>net.sf.json-lib</groupId>
	    <artifactId>json-lib</artifactId>
	    <version>2.4</version>
		<exclusions>
			<exclusion>
				<groupId>log4j</groupId>
				<artifactId>log4j</artifactId>
			</exclusion>
			<exclusion>
				<groupId>commons-beanutils</groupId>
				<artifactId>commons-beanutils</artifactId>
			</exclusion>
			<exclusion>
				<groupId>commons-collections</groupId>
				<artifactId>commons-collections</artifactId>
			</exclusion>
		</exclusions>	    
	</dependency>
	
	<dependency>
	    <groupId>com.fasterxml.jackson.core</groupId>
	    <artifactId>jackson-core</artifactId>
	    <version>2.18.2</version>
	</dependency>

	<dependency>
	    <groupId>com.fasterxml.jackson.core</groupId>
	    <artifactId>jackson-databind</artifactId>
	    <version>2.18.2</version>
	</dependency>

	<dependency>
		<groupId>net.sf.json-lib</groupId>
		<artifactId>json-lib-ext-spring</artifactId>
		<version>1.0.2</version>
		<exclusions>
			<exclusion>
				<groupId>log4j</groupId>
				<artifactId>log4j</artifactId>
			</exclusion>
		</exclusions>			
	</dependency>

	<!-- POI -->
	<dependency>
	    <groupId>org.apache.poi</groupId>
	    <artifactId>poi</artifactId>
	    <version>5.3.0</version>
	</dependency>

	<dependency>
	    <groupId>org.apache.poi</groupId>
	    <artifactId>poi-ooxml</artifactId>
	    <version>5.3.0</version>
	</dependency>

	<!-- Rest Client -->
	<dependency>
	    <groupId>com.squareup.retrofit2</groupId>
	    <artifactId>retrofit</artifactId>
	    <version>2.9.0</version>
	</dependency>
	
	<dependency>
	    <groupId>com.squareup.retrofit2</groupId>
	    <artifactId>converter-gson</artifactId>
	    <version>2.9.0</version>
	</dependency>
			
	<!-- DB 연동 -->
	<dependency>
	    <groupId>mysql</groupId>
	    <artifactId>mysql-connector-java</artifactId>
	    <version>8.0.33</version>
	</dependency>

	<dependency>
		<groupId>org.springframework</groupId>
		<artifactId>spring-jdbc</artifactId>
		<version>${org.springframework-version}</version>
	</dependency>
    
	<dependency>
	    <groupId>org.mybatis</groupId>
	    <artifactId>mybatis</artifactId>
	    <version>3.5.17</version>
	</dependency>
	
	<dependency>
	    <groupId>org.apache.commons</groupId>
	    <artifactId>commons-dbcp2</artifactId>
	    <version>2.13.0</version>
	</dependency>


	<dependency>
	    <groupId>org.mybatis</groupId>
	    <artifactId>mybatis-spring</artifactId>
	    <version>3.0.4</version>
	</dependency>

	<!-- AesCrypto 암호화, 복호화 -->
	<dependency>
		<groupId>org.jasypt</groupId>
		<artifactId>jasypt-spring3</artifactId>
		<version>1.9.3</version>
	</dependency>

	<dependency>
		<groupId>org.bouncycastle</groupId>
		<artifactId>bcprov-jdk15to18</artifactId>
		<version>1.78.1</version>
	</dependency>
		
	<!-- 웹 크롤링 -->
	<dependency>
	    <groupId>org.seleniumhq.selenium</groupId>
	    <artifactId>selenium-java</artifactId>
	    <version>4.28.1</version>
	</dependency>
	
	<dependency>
	    <groupId>org.seleniumhq.selenium</groupId>
	    <artifactId>selenium-chrome-driver</artifactId>
	    <version>4.28.1</version>
	</dependency>
	
	<!-- 네이버스토어 연동 관련 -->
	<dependency>
	    <groupId>org.mindrot</groupId>
	    <artifactId>jbcrypt</artifactId>
	    <version>0.4</version>
	</dependency>

	<!-- 문자 발송 -->
	<dependency>
		<groupId>net.nurigo</groupId>
		<artifactId>sdk</artifactId>
		<version>4.3.2</version>
	</dependency>

	<dependency>
		<groupId>com.squareup.okhttp3</groupId>
		<artifactId>okhttp</artifactId>
		<version>4.12.0</version>
	</dependency>

  	<!-- Test -->
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>3.8.1</version>
      <scope>test</scope>
    </dependency>
  </dependencies>
  
  <build>
    <finalName>${project.artifactId}_${env}_${timestamp}</finalName>
	<pluginManagement>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.11.0</version>
                <configuration>
                    <source>21</source>
                    <target>21</target>
                    <encoding>UTF-8</encoding>
                </configuration>
            </plugin>
        </plugins>
    </pluginManagement>
    <resources>
    	<resource>
    		<directory>src/main/resources.${env}</directory>
    	</resource>
    	<resource>
            <directory>src/main/java</directory>
            <includes>                      
                <include>**/*.xml</include>
            </includes>
        </resource>
    </resources>
  </build>
  
	<profiles>
		<profile>
			<id>real</id>
			<properties>
				<env>real</env>
			</properties>
		</profile>
		<profile>
			<id>dev</id>
			<properties>
				<env>dev</env>
			</properties>
		</profile>
	</profiles>
  
</project>
