###################### DB 설정 ######################
######## 접속 관련 정보 ########
driverClassName=com.mysql.cj.jdbc.Driver
url=jdbc:mysql://172.17.0.2:3306/forYuum?useSSL=false&allowPublicKeyRetrieval=true

######## 설정 관련 정보 ########
# 미사용 커넥션의 반환 전 대기 시간 (초)
removeAbandonedTimeout=300
# 초기에 생성되는 커넥션의 개수
initialSize=20
# 커넥션 풀이 제공할 최대 커넥션의 개수
maxTotal=120
# 풀에 커넥션이 존재하지 않을 때, 커넥션이 다시 풀에 리턴될 때까지 대기시간, 1/1000초 단위, -1일 경우 무한대기
maxWaitMillis=15000
# 사용되지 않고 풀에 저장될 수 있는 최대 커넥션 개수, 음수일 경우 제한이 없다.
maxIdle=20
# 사용되지 않고 풀에 저장될 수 있는 최소 커넥션 개수, 음수일 경우 제한이 없다.
minIdle=10
# true 일 경우 커넥션 풀에서 커넥션을 가져올 때 커넥션이 유효한지의 여부 검사
testOnBorrow=true
# 사용되지 않는 커넥션을 몇 개 검사할 지 지정
numTestsPerEvictionRun=2
# true 일 경우 비활성화 커넥션을 추출할 때 커넥션이 유효한지의 여부를 검사해서 유효하지 않은 커넥션은 풀에서 제거
testWhileIdle=true
# 사용되지 않은 커넥션을 추출하는 쓰레드의 실행주기를 지정한다. 양수가 아닌경우 실행되지 않는다.
timeBetweenEvictionRunsMillis=30000